# Generated by Django 5.1.15 on 2026-08-16 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Human-readable table identifier (e.g. T01, Table 12, VIP-1)', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Seating capacity for guests (minimum 1)')),
                ('section', models.CharField(blank=True, default='Main Dining', help_text='Floor plan area or zone (e.g. Main Dining, Patio, Bar, Rooftop, VIP)', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='AVAILABLE', help_text='Current operational table status', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Operational lifecycle presence (Inactive tables are hidden from floor plans)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Deterministic display order on POS terminals and floor grids')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this table', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'ordering': ['section', 'display_order', 'name'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='tables_rest_restaur_b25b20_idx'), models.Index(fields=['restaurant', 'is_active'], name='tables_rest_restaur_187dea_idx'), models.Index(fields=['restaurant', 'section'], name='tables_rest_restaur_d21c0e_idx'), models.Index(fields=['restaurant', 'display_order'], name='tables_rest_restaur_b6d719_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_table_name_per_restaurant'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='check_positive_table_capacity')],
            },
        ),
    ]
