# Generated by Django 5.1.15 on 2026-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='qr_code_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Secure token for table QR scanning and dine-in mobile ordering', max_length=64),
        ),
    ]
