# Generated by Django 5.1.15 on 2026-08-16 17:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('po_number', models.CharField(help_text='Sequential human-readable PO number (e.g. PO-000001)', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Lifecycle state of the purchase order', max_length=30)),
                ('order_date', models.DateField(blank=True, help_text='Date the purchase order was issued', null=True)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected shipment arrival date', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross total of line items before tax', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchasing tax amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net total procurement cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, default='', help_text='Delivery instructions or internal comments')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp of managerial approval', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved the purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the PO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restaurant tenant', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('item_name_snapshot', models.CharField(help_text='Snapshot of ingredient name at PO creation', max_length=200)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, help_text='Total quantity ordered', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box')], help_text='Unit of measurement', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total line cost (quantity_ordered * unit_cost)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity_received', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Cumulative quantity physically received into inventory', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('inventory_item', models.ForeignKey(help_text='Target raw material catalog item', on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(help_text='Parent purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('receipt_number', models.CharField(help_text='Sequential receipt number (e.g. REC-000001)', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Client deduplication token', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_receipts', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Purchase Receipt',
                'verbose_name_plural': 'Purchase Receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box')], max_length=20)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='procurement.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchasereceipt')),
            ],
            options={
                'verbose_name': 'Purchase Receipt Item',
                'verbose_name_plural': 'Purchase Receipt Items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('supplier_code', models.CharField(help_text='Human-readable unique code (e.g. SUP-000001)', max_length=32)),
                ('name', models.CharField(help_text='Supplier business / company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', help_text='Primary sales rep or contact person', max_length=150)),
                ('email', models.EmailField(blank=True, default='', help_text='Supplier contact email', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Supplier phone number', max_length=30)),
                ('address', models.TextField(blank=True, default='', help_text='Physical delivery / warehouse address')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes or terms')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-deactivation flag')),
                ('restaurant', models.ForeignKey(help_text='Restaurant tenant', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Target vendor supplier', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['restaurant', 'is_active'], name='procurement_restaur_00376c_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'supplier_code'), name='unique_supplier_code_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['restaurant', 'status'], name='procurement_restaur_3d0481_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['restaurant', 'created_at'], name='procurement_restaur_45ac01_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('restaurant', 'po_number'), name='unique_po_number_per_restaurant'),
        ),
    ]
