# Generated by Django 5.1.15 on 2026-08-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], help_text='Unit of measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], max_length=20),
        ),
    ]
