# Generated by Django 5.1.15 on 2026-08-17 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorybatch_inventorytransfer_and_more'),
        ('procurement', '0002_alter_purchaseorderitem_unit_and_more'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='e.g. Kitchen Food & Beverage Q3 Budget', max_length=150)),
                ('location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='MAIN_STORE', max_length=30)),
                ('department', models.CharField(blank=True, default='Kitchen', max_length=100)),
                ('category', models.CharField(blank=True, default='ALL', max_length=100)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom Period')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount committed on approved / open POs', max_digits=12)),
                ('actual_spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount invoiced / received', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Procurement Budget',
                'verbose_name_plural': 'Procurement Budgets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot_data', models.JSONField(help_text='Full serialized state of PO and lines at this version')),
                ('change_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Purchase Order Version',
                'verbose_name_plural': 'Purchase Order Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('requisition_number', models.CharField(help_text='Unique requisition number (e.g. REQ-20260817-XXXX)', max_length=32)),
                ('location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='KITCHEN', max_length=30)),
                ('required_date', models.DateField(blank=True, help_text='Required date by kitchen line', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('URGENT', 'Urgent (Low Stock)'), ('EMERGENCY', 'Emergency (Stockout)')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CONVERTED_TO_PO', 'Converted to PO')], db_index=True, default='DRAFT', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], max_length=20)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Purchase Requisition Item',
                'verbose_name_plural': 'Purchase Requisition Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('return_number', models.CharField(help_text='Unique return number (e.g. RET-20260817-XXXX)', max_length=32)),
                ('status', models.CharField(choices=[('REQUESTED', 'Return Requested'), ('APPROVED', 'Approved by Manager'), ('DISPATCHED', 'Goods Dispatched to Supplier'), ('COMPLETED', 'Completed & Credit Issued'), ('REJECTED', 'Rejected by Supplier')], db_index=True, default='REQUESTED', max_length=30)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged Goods'), ('WRONG_ITEM', 'Wrong Item Delivered'), ('EXPIRED', 'Expired Product'), ('QUALITY_ISSUE', 'Quality Issue / Defect'), ('OVER_DELIVERY', 'Excess Over-Delivery'), ('OTHER', 'Other')], default='DAMAGED', max_length=30)),
                ('total_credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Purchase Return Item',
                'verbose_name_plural': 'Purchase Return Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, default='Account Rep', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier Contact',
                'verbose_name_plural': 'Supplier Contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('credit_note_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Available'), ('APPLIED', 'Applied to Invoices'), ('REFUNDED', 'Refunded in Cash'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('issued_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Supplier Credit',
                'verbose_name_plural': 'Supplier Credits',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', '3-Way Match Passed'), ('PARTIAL_MATCH', 'Partial Match'), ('VARIANCE', 'Price / Qty Variance Detected'), ('REQUIRES_REVIEW', 'Managerial Review Required'), ('REJECTED', 'Invoice Rejected')], db_index=True, default='UNMATCHED', max_length=30)),
                ('quantity_variance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('price_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('quantity_invoiced', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Supplier Invoice Item',
                'verbose_name_plural': 'Supplier Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('supplier_sku', models.CharField(blank=True, default='', help_text='Vendor product catalog SKU / barcode', max_length=100)),
                ('purchase_unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], default='kg', help_text='Unit vendor sells in (e.g. Box, Case, Bag, kg)', max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='1 Purchase Unit = X Inventory Stock Units', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Negotiated purchase price per purchase unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_order_quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Vendor Minimum Order Quantity (MOQ)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('pack_size', models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Package quantity increments (e.g. pack of 6 or 12)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('lead_time_days', models.PositiveIntegerField(default=2, help_text='Item-specific delivery lead time')),
                ('is_preferred', models.BooleanField(default=False, help_text='Primary preferred supplier for this ingredient')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier Item',
                'verbose_name_plural': 'Supplier Items',
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('previous_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], default='kg', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Supplier Price History',
                'verbose_name_plural': 'Supplier Price Histories',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledgement_status',
            field=models.CharField(choices=[('PENDING', 'Pending Acknowledgement'), ('ACCEPTED', 'Accepted in Full'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('REJECTED', 'Rejected by Vendor'), ('DELIVERY_DATE_CHANGED', 'Rescheduled Delivery')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Special vendor discount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='location',
            field=models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='MAIN_STORE', help_text='Target receiving storage location', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(choices=[('IMMEDIATE', 'Due on Receipt / Cash'), ('NET_7', 'Net 7 Days'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_60', 'Net 60 Days'), ('COD', 'Cash on Delivery'), ('PREPAID', 'Prepaid / Advance')], default='NET_30', max_length=30),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Revision sequence number'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='delivery_note_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='invoice_number',
            field=models.CharField(blank=True, default='', help_text='Vendor delivery invoice number', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='storage_location',
            field=models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='MAIN_STORE', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='quantity_accepted',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Accepted quantity booked into usable inventory', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='quantity_rejected',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Rejected quantity turned away at the loading dock', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='rejection_reason',
            field=models.CharField(choices=[('NONE', 'Accepted / No Defect'), ('DAMAGED', 'Damaged / Broken'), ('EXPIRED', 'Expired / Short Expiry'), ('WRONG_ITEM', 'Wrong Product Shipped'), ('SUBSTANDARD_QUALITY', 'Substandard / Spoiled Quality'), ('OVER_DELIVERY', 'Excess Over-Delivery')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasereceiptitem',
            name='unit_cost_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual invoiced cost per unit', max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='USD', help_text='Invoicing currency', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=2, help_text='Standard vendor fulfillment lead time in days'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order value threshold for free delivery', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(choices=[('IMMEDIATE', 'Due on Receipt / Cash'), ('NET_7', 'Net 7 Days'), ('NET_15', 'Net 15 Days'), ('NET_30', 'Net 30 Days'), ('NET_60', 'Net 60 Days'), ('COD', 'Cash on Delivery'), ('PREPAID', 'Prepaid / Advance')], default='NET_30', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('PRIMARY_WHOLESALER', 'Primary Wholesaler'), ('LOCAL_PRODUCE', 'Local Farm / Produce'), ('SPECIALTY_IMPORTER', 'Specialty Importer'), ('BEVERAGE_DISTRIBUTOR', 'Beverage Distributor'), ('PACKAGING_SUPPLIER', 'Packaging & Paper Goods'), ('OTHER', 'Other Vendor')], db_index=True, default='PRIMARY_WHOLESALER', max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax / VAT / GST Registration number', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent to Vendor'), ('ACKNOWLEDGED', 'Vendor Acknowledged'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', help_text='Lifecycle state of the purchase order', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, help_text='Total physical quantity delivered by driver', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes or special vendor terms'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['restaurant', 'expected_delivery_date'], name='procurement_restaur_95f476_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['restaurant', 'supplier_type'], name='procurement_restaur_06db93_idx'),
        ),
        migrations.AddField(
            model_name='procurementbudget',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_budgets', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='purchaseorderversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderversion',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='converted_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requisitions', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='procurement.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchasereturn'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='related_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='related_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='procurement.purchasereturn'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credits', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoiced_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_items', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierpricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpricehistory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_price_history', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplierpricehistory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='procurement.supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('restaurant', 'requisition_number'), name='unique_req_num_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('restaurant', 'return_number'), name='unique_return_num_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='supplieritem',
            index=models.Index(fields=['inventory_item', 'is_preferred'], name='procurement_invento_36b023_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('supplier', 'inventory_item'), name='unique_supplier_inventory_item'),
        ),
    ]
