# Generated by Django 5.1.15 on 2026-08-16 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('status', models.CharField(choices=[('CONSUMED', 'Consumed'), ('REVERSED', 'Reversed')], default='CONSUMED', max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_consumption', to='orders.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_consumptions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Inventory Consumption Record',
                'verbose_name_plural': 'Inventory Consumption Records',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Ingredient name (e.g. Basmati Rice, Chicken Breast, Extra Virgin Olive Oil)', max_length=200)),
                ('sku', models.CharField(blank=True, default='', help_text='Stock keeping unit barcode or internal code', max_length=50)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box')], default='kg', help_text='Primary unit of measurement for stock tracking', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Current available stock balance', max_digits=12)),
                ('minimum_stock_level', models.DecimalField(decimal_places=3, default=Decimal('5.000'), help_text='Reorder threshold below which status becomes LOW_STOCK', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average purchase cost per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Soft-deactivation flag')),
                ('restaurant', models.ForeignKey(help_text='Restaurant owning this inventory stock', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('yield_quantity', models.PositiveIntegerField(default=1, help_text='Number of dish portions produced by this recipe', validators=[django.core.validators.MinValueValidator(1)])),
                ('instructions', models.TextField(blank=True, default='', help_text='Preparation / cooking instructions')),
                ('menu_item', models.OneToOneField(help_text='Catalog menu item prepared by this recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='menu.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of ingredient consumed per recipe portion', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box')], help_text='Measurement unit for the ingredient', max_length=20)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.inventoryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase / Stock Intake'), ('ADJUSTMENT_IN', 'Positive Adjustment'), ('ADJUSTMENT_OUT', 'Negative Adjustment'), ('CONSUMPTION', 'Order Recipe Consumption'), ('WASTAGE', 'Wastage / Spoilage'), ('RETURN', 'Return / Compensation')], db_index=True, help_text='Type of stock transaction', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity delta applied (signed: positive or negative)', max_digits=12)),
                ('quantity_before', models.DecimalField(decimal_places=3, help_text='Stock quantity balance prior to movement', max_digits=12)),
                ('quantity_after', models.DecimalField(decimal_places=3, help_text='Stock quantity balance after movement', max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box')], help_text='Unit of measurement used', max_length=20)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Reference category (e.g. ORDER, MANUAL, WASTAGE)', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Source identifier (e.g. Order UUID or ORD-000123)', max_length=128)),
                ('reason', models.TextField(blank=True, default='', help_text='Staff remarks or wastage reason')),
                ('created_by', models.ForeignKey(blank=True, help_text='Employee who performed the stock action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='Target inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization', on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'is_active'], name='inventory_i_restaur_db4020_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_inventory_item_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('recipe', 'inventory_item'), name='unique_recipe_ingredient'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['restaurant', 'movement_type'], name='inventory_s_restaur_7e4196_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['restaurant', 'created_at'], name='inventory_s_restaur_6ef921_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'created_at'], name='inventory_s_item_id_a9fe64_idx'),
        ),
    ]
