# Generated by Django 5.1.15 on 2026-08-17 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('batch_number', models.CharField(help_text='Lot / Batch number (e.g. LOT-2026-0817-A)', max_length=100)),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='Date batch arrived into inventory')),
                ('expiry_date', models.DateField(blank=True, db_index=True, help_text='Best before / expiration date', null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, help_text='Original received quantity in stock units', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('current_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Remaining quantity in stock units', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Specific purchase cost per unit for this batch', max_digits=12)),
                ('supplier_name', models.CharField(blank=True, default='', help_text='Supplier from which batch was procured', max_length=200)),
                ('storage_location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='MAIN_STORE', help_text='Location storing this batch', max_length=40)),
                ('batch_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted')], db_index=True, default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory Batch',
                'verbose_name_plural': 'Inventory Batches',
                'ordering': ['expiry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('transfer_number', models.CharField(help_text='Sequential transfer identifier (e.g. TR-000101)', max_length=32)),
                ('source_location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='MAIN_STORE', max_length=40)),
                ('destination_location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='KITCHEN', max_length=40)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received & Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Inventory Transfer',
                'verbose_name_plural': 'Inventory Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Inventory Transfer Item',
                'verbose_name_plural': 'Inventory Transfer Items',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('count_number', models.CharField(help_text='Audit session identifier (e.g. SC-000101)', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved & Reconciled'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('location', models.CharField(default='ALL', help_text='Target storage location or ALL', max_length=40)),
                ('category', models.CharField(default='ALL', help_text='Item category or ALL', max_length=40)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Stock Count',
                'verbose_name_plural': 'Stock Counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('system_quantity', models.DecimalField(decimal_places=3, help_text='Expected book quantity at count creation', max_digits=12)),
                ('counted_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Physically counted quantity', max_digits=12)),
                ('variance_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Counted minus system quantity', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Unit cost applied for variance valuation', max_digits=12)),
                ('variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monetary value of variance (variance_quantity * unit_cost)', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Stock Count Item',
                'verbose_name_plural': 'Stock Count Items',
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], max_length=20)),
                ('reason', models.CharField(choices=[('SPOILAGE', 'Expired / Spoiled'), ('PREPARATION_WASTE', 'Preparation / Trimming Waste'), ('DAMAGED', 'Damaged / Dropped'), ('SPILLAGE', 'Spillage / Accident'), ('OVER_PORTIONING', 'Over-Portioning Loss'), ('BURNT_OVERCOOKED', 'Burnt / Cooking Error'), ('CUSTOMER_RETURN', 'Customer Plate Return'), ('OTHER', 'Other Reason')], db_index=True, default='SPOILAGE', max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Unit cost applied to calculate shrinkage loss', max_digits=12)),
                ('total_loss_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Financial loss value (quantity * unit_cost)', max_digits=12)),
                ('location', models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], default='KITCHEN', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Waste Record',
                'verbose_name_plural': 'Waste Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='recipeitem',
            name='unique_recipe_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('RAW_INGREDIENT', 'Raw Ingredient'), ('PACKAGING', 'Packaging'), ('CONSUMABLE', 'Consumable'), ('SEMI_FINISHED', 'Semi-Finished Good / Prep'), ('FINISHED_GOOD', 'Finished Good')], db_index=True, default='RAW_INGREDIENT', help_text='Item classification', max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_purchase_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit cost on the most recent purchase invoice', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('100.000'), help_text='Maximum holding capacity', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='par_level',
            field=models.DecimalField(decimal_places=3, default=Decimal('10.000'), help_text='Ideal target inventory level for replenishment planning', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_to_stock_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Conversion multiplier from purchase unit to stock unit (e.g. 1 Box = 24 Pieces)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], default='kg', help_text='Default purchasing unit from supplier', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_condition',
            field=models.CharField(choices=[('AMBIENT', 'Ambient Room Temp'), ('REFRIGERATED', 'Refrigerated (0-4°C)'), ('FROZEN', 'Frozen (-18°C)'), ('DRY', 'Cool & Dry')], default='AMBIENT', help_text='Storage climate requirement', max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(choices=[('MAIN_STORE', 'Main Storage / Warehouse'), ('KITCHEN', 'Kitchen Prep Line'), ('BAR', 'Bar Station'), ('WALK_IN_FREEZER', 'Walk-In Freezer'), ('DRY_STORAGE', 'Dry Storage'), ('OTHER', 'Other Location')], db_index=True, default='MAIN_STORE', help_text='Primary physical storage location', max_length=40),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='track_batch',
            field=models.BooleanField(default=False, help_text='Flag indicating individual batch / lot numbers must be allocated'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='track_expiry',
            field=models.BooleanField(default=False, help_text='Flag indicating expiry dates must be monitored'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weighted_average_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Moving weighted average valuation cost per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Usable yield percentage after preparation / trimming', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moisture / cooking shrinkage loss percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='effective_from',
            field=models.DateTimeField(blank=True, help_text='Timestamp when version becomes active', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='effective_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp when version is deprecated', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', help_text='Descriptive recipe / preparation name', max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Chef / kitchen internal notes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Total portion count or output weight/volume generated', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output_unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], default='portion', help_text='Unit of recipe output', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_loss_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected trim/peeling loss percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99.00'))]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('MENU_ITEM_RECIPE', 'Menu Item Dish BOM'), ('SUB_RECIPE', 'Sub-Recipe / Sauce / Patty Prep'), ('PREPARATION_BATCH', 'Bulk Preparation Batch')], db_index=True, default='MENU_ITEM_RECIPE', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Sequential version number (e.g. 1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Net usable yield percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='preparation_notes',
            field=models.CharField(blank=True, default='', help_text='Specific cut or prep note (e.g. diced, chopped finely)', max_length=255),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='sub_recipe',
            field=models.ForeignKey(blank=True, help_text='Sub-recipe component (if nested prep BOM)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_recipe_usages', to='inventory.recipe'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Historical cost per unit at transaction time', max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current reference purchase cost per stock unit', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], default='kg', help_text='Primary unit of measurement for stock tracking', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='menu_item',
            field=models.ForeignKey(blank=True, help_text='Associated menu catalog item (if dish BOM)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Raw material ingredient (if direct item)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity consumed per recipe batch output', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], help_text='Measurement unit for the ingredient', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase / Stock Intake'), ('ADJUSTMENT_IN', 'Positive Adjustment'), ('ADJUSTMENT_OUT', 'Negative Adjustment'), ('CONSUMPTION', 'Order Recipe Consumption'), ('WASTAGE', 'Wastage / Scrap'), ('SPOILAGE', 'Expired / Spoilage'), ('RETURN', 'Return / Compensation'), ('TRANSFER_IN', 'Transfer Received'), ('TRANSFER_OUT', 'Transfer Dispatched'), ('PRODUCTION_IN', 'Production Yield In'), ('PRODUCTION_OUT', 'Production BOM Consumed')], db_index=True, help_text='Type of stock transaction', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(blank=True, default='', help_text='Reference category (e.g. ORDER, MANUAL, WASTAGE, TRANSFER, COUNT)', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('piece', 'Piece (pc)'), ('portion', 'Portion'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('box', 'Box'), ('oz', 'Ounce (oz)'), ('lb', 'Pound (lb)')], help_text='Unit of measurement used', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'item_type'], name='inventory_i_restaur_dd308b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'storage_location'], name='inventory_i_restaur_2400a4_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['restaurant', 'status'], name='inventory_r_restaur_619084_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['menu_item', 'status'], name='inventory_r_menu_it_e9db6b_idx'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='item',
            field=models.ForeignKey(help_text='Inventory item', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='restaurant',
            field=models.ForeignKey(help_text='Restaurant tenant', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Specific batch impacted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='inventorytransferitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorytransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorytransfer'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_records', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='inventory.inventorybatch'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_waste_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['restaurant', 'batch_status'], name='inventory_i_restaur_7b786e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybatch',
            index=models.Index(fields=['item', 'expiry_date'], name='inventory_i_item_id_5d05c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransfer',
            constraint=models.UniqueConstraint(fields=('restaurant', 'transfer_number'), name='unique_transfer_number_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(fields=('restaurant', 'count_number'), name='unique_count_number_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['restaurant', 'reason'], name='inventory_w_restaur_6931fd_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['restaurant', 'created_at'], name='inventory_w_restaur_4c6d8d_idx'),
        ),
    ]
