# Generated by Django 5.1.15 on 2026-08-16 18:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('notification_type', models.CharField(choices=[('INVENTORY_LOW_STOCK', 'Low Stock Alert'), ('INVENTORY_OUT_OF_STOCK', 'Out of Stock Alert'), ('PURCHASE_ORDER_PENDING', 'PO Pending Approval'), ('PURCHASE_ORDER_APPROVED', 'PO Approved'), ('PURCHASE_ORDER_PARTIALLY_RECEIVED', 'PO Partially Received'), ('PURCHASE_ORDER_RECEIVED', 'PO Fully Received'), ('ORDER_NEW', 'New Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('KDS_READY', 'Kitchen Ticket Ready'), ('PAYMENT_COMPLETED', 'Payment Settled'), ('SYSTEM_ALERT', 'System Alert')], db_index=True, default='SYSTEM_ALERT', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(help_text='Notification heading', max_length=200)),
                ('message', models.TextField(help_text='Notification detailed body')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Read acknowledgment status')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', help_text='Client route path (e.g. /inventory/items/123)', max_length=255)),
                ('entity_type', models.CharField(blank=True, default='', help_text='Originating model name (e.g. inventory_item, purchase_order)', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', help_text='Originating entity UUID/ID', max_length=64)),
                ('deduplication_key', models.CharField(blank=True, db_index=True, default='', help_text='State deduplication hash', max_length=128)),
                ('recipient', models.ForeignKey(help_text='Staff recipient user', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Tenant context', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'recipient', 'is_read', 'created_at'], name='notificatio_restaur_59abbd_idx'), models.Index(fields=['restaurant', 'deduplication_key'], name='notificatio_restaur_c6d849_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('realtime_enabled', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('order_alerts', models.BooleanField(default=True)),
                ('procurement_alerts', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'user'), name='unique_user_notification_preference')],
            },
        ),
    ]
