# Generated by Django 5.1.15 on 2026-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INVENTORY_LOW_STOCK', 'Low Stock Alert'), ('INVENTORY_OUT_OF_STOCK', 'Out of Stock Alert'), ('PURCHASE_ORDER_PENDING', 'PO Pending Approval'), ('PURCHASE_ORDER_APPROVED', 'PO Approved'), ('PURCHASE_ORDER_PARTIALLY_RECEIVED', 'PO Partially Received'), ('PURCHASE_ORDER_RECEIVED', 'PO Fully Received'), ('ORDER_NEW', 'New Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('KDS_READY', 'Kitchen Ticket Ready'), ('PAYMENT_COMPLETED', 'Payment Settled'), ('DELIVERY_ASSIGNED', 'Delivery Assigned'), ('DELIVERY_DISPATCHED', 'Out for Delivery'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_DELAYED', 'Delivery Delayed'), ('SYSTEM_ALERT', 'System Alert')], db_index=True, default='SYSTEM_ALERT', max_length=50),
        ),
    ]
