# Generated by Django 5.1.15 on 2026-08-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INVENTORY_LOW_STOCK', 'Low Stock Alert'), ('INVENTORY_OUT_OF_STOCK', 'Out of Stock Alert'), ('PURCHASE_ORDER_PENDING', 'PO Pending Approval'), ('PURCHASE_ORDER_APPROVED', 'PO Approved'), ('PURCHASE_ORDER_PARTIALLY_RECEIVED', 'PO Partially Received'), ('PURCHASE_ORDER_RECEIVED', 'PO Fully Received'), ('ORDER_NEW', 'New Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('KDS_READY', 'Kitchen Ticket Ready'), ('PAYMENT_COMPLETED', 'Payment Settled'), ('DELIVERY_ASSIGNED', 'Delivery Assigned'), ('DELIVERY_DISPATCHED', 'Out for Delivery'), ('DELIVERY_COMPLETED', 'Delivery Completed'), ('DELIVERY_FAILED', 'Delivery Failed'), ('DELIVERY_DELAYED', 'Delivery Delayed'), ('INVENTORY_EXPIRY_WARNING', 'Expiry Warning'), ('INVENTORY_EXPIRED', 'Expired Stock Alert'), ('STOCK_COUNT_SUBMITTED', 'Stock Count Submitted'), ('STOCK_TRANSFER_REQUESTED', 'Stock Transfer Requested'), ('PURCHASE_REQUISITION_SUBMITTED', 'Requisition Submitted'), ('PURCHASE_REQUISITION_APPROVED', 'Requisition Approved'), ('PURCHASE_ORDER_SENT', 'PO Sent to Vendor'), ('PURCHASE_ORDER_OVERDUE', 'PO Shipment Overdue'), ('PURCHASE_RETURN_CREATED', 'Purchase Return Initiated'), ('BUDGET_THRESHOLD_REACHED', 'Procurement Budget Warning'), ('INVOICE_VARIANCE_DETECTED', 'Invoice Match Discrepancy'), ('CASH_DRAWER_VARIANCE', 'Cash Drawer Variance Alert'), ('EXPENSE_PENDING_APPROVAL', 'Expense Claim Pending Approval'), ('EXPENSE_APPROVED', 'Expense Claim Approved'), ('PERIOD_CLOSE_REQUIRED', 'Financial Period Close Due'), ('INVOICE_OVERDUE', 'Receivable / Payable Overdue'), ('UNBALANCED_JOURNAL_ALERT', 'Accounting Integrity Discrepancy'), ('SHIFT_ASSIGNED', 'Shift Assigned'), ('SHIFT_CHANGED', 'Shift Schedule Changed'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('SHIFT_SWAP_REQUESTED', 'Shift Swap Requested'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('ATTENDANCE_CORRECTION_REQUESTED', 'Attendance Correction Requested'), ('OVERTIME_PENDING_APPROVAL', 'Overtime Pending Approval'), ('PAYROLL_APPROVED', 'Payroll Approved'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('PAYSLIP_AVAILABLE', 'New Payslip Available'), ('STAFFING_GAP_ALERT', 'Staffing Gap Alert'), ('SYSTEM_ALERT', 'System Alert')], db_index=True, default='SYSTEM_ALERT', max_length=50),
        ),
    ]
