# Generated by Django 5.1.15 on 2026-08-16 12:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('employee_id', models.CharField(db_index=True, help_text='Restaurant-unique employee identifier code (e.g. EMP-001)', max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', help_text='Staff employment status (ACTIVE or DISABLED)', max_length=20)),
                ('membership', models.OneToOneField(help_text='Tenant membership record managing active authorization scope', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='rbac.tenantmembership')),
                ('primary_role', models.ForeignKey(help_text='Exactly ONE primary operational role governing default dashboard and initial login scope', on_delete=django.db.models.deletion.PROTECT, related_name='primary_staff_members', to='rbac.role')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization employing this staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='restaurants.restaurant')),
                ('secondary_roles', models.ManyToManyField(blank=True, help_text='Zero or more secondary operational roles available for active role switching', related_name='secondary_staff_members', to='rbac.role')),
                ('user', models.ForeignKey(help_text='Underlying user authentication account', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['employee_id'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='staff_staff_restaur_6b8f7e_idx'), models.Index(fields=['restaurant', 'email'], name='staff_staff_restaur_c9de8f_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'employee_id'), name='unique_employee_id_per_restaurant'), models.UniqueConstraint(fields=('restaurant', 'user'), name='unique_user_per_restaurant_staff')],
            },
        ),
    ]
