# Generated by Django 5.1.15 on 2026-08-17 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0002_restauranttable_qr_code_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('guest_session_id', models.CharField(db_index=True, help_text='Client browser session identifier for guest diners', max_length=64)),
                ('order_type', models.CharField(default='DINE_IN', help_text='Intended fulfillment type (DINE_IN, TAKEAWAY)', max_length=20)),
                ('items_json', models.JSONField(blank=True, default=list, help_text='Serialized cart item payloads: [{menu_item_id, quantity, notes, modifiers}]')),
                ('coupon_code', models.CharField(blank=True, default='', help_text='Applied voucher/coupon code', max_length=50)),
                ('special_instructions', models.TextField(blank=True, default='', help_text='General order instructions')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Cart session expiration timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Linked authenticated customer account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_sessions', to='customers.customer')),
                ('restaurant', models.ForeignKey(help_text='Restaurant tenant where cart is open', on_delete=django.db.models.deletion.CASCADE, related_name='cart_sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, help_text='Assigned dining table for QR table orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_sessions', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Cart Session',
                'verbose_name_plural': 'Cart Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'guest_session_id'], name='ordering_ca_restaur_b9ca3e_idx'), models.Index(fields=['restaurant', 'customer'], name='ordering_ca_restaur_4b5f8f_idx'), models.Index(fields=['expires_at', 'is_active'], name='ordering_ca_expires_8bcea5_idx')],
            },
        ),
    ]
