# Generated by Django 5.1.15 on 2026-08-16 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('name', models.CharField(help_text='Primary trading / commercial name of the restaurant', max_length=200)),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal business entity name', max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL-safe restaurant identifier slug', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Official business contact email', max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text="IANA timezone string (e.g. 'America/New_York', 'Asia/Kolkata')", max_length=50)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 Currency code (e.g. USD, EUR, GBP, INR)', max_length=10)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='restaurants_slug_d8b6eb_idx'), models.Index(fields=['is_active'], name='restaurants_is_acti_38f6bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Indicates whether the restaurant is closed all day on this day')),
                ('is_overnight', models.BooleanField(default=False, help_text='Indicates operating hours extend past midnight into next day')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'ordering': ['restaurant', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'day_of_week'), name='unique_business_hour_day_per_restaurant')],
            },
        ),
    ]
