# Generated by Django 5.1.15 on 2026-08-16 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', help_text='Current kitchen preparation state', max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Preparation priority (0=Normal, 1=High, 2=Rush/VIP)')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when kitchen staff started meal preparation', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='Timestamp when meal preparation finished and was placed on pass', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when order was served/collected by waiter', null=True)),
                ('order', models.OneToOneField(help_text='Source customer order record', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_ticket', to='orders.order')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this kitchen ticket', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Kitchen Ticket',
                'verbose_name_plural': 'Kitchen Tickets',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='kitchen_kit_restaur_2a1d31_idx'), models.Index(fields=['restaurant', 'created_at'], name='kitchen_kit_restaur_b92f74_idx')],
            },
        ),
    ]
