# Generated by Django 5.1.15 on 2026-08-18 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('encrypted_secret', models.CharField(help_text='Fernet-encrypted TOTP secret key', max_length=255)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Whether the device has been verified with an initial TOTP code')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether MFA is actively enforced for this user')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the recovery code', max_length=64)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='security.mfadevice')),
            ],
            options={
                'verbose_name': 'MFA Recovery Code',
                'verbose_name_plural': 'MFA Recovery Codes',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'Login Success'), ('AUTH_LOGIN_FAILED', 'Login Failed'), ('AUTH_LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET_REQUESTED', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('MFA_VERIFIED', 'MFA Verified'), ('MFA_FAILED', 'MFA Verification Failed'), ('SESSION_REVOKED', 'Session Revoked'), ('ALL_SESSIONS_REVOKED', 'All Sessions Revoked'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('ACCOUNT_DISABLED', 'Account Disabled'), ('ACCOUNT_DELETED', 'Account Deleted'), ('PERMISSION_DENIED', 'Permission Denied'), ('ROLE_CHANGED', 'Role Changed'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SECURITY_SETTING_CHANGED', 'Security Setting Changed'), ('DATA_EXPORT', 'Sensitive Data Export'), ('ADMIN_SESSION_REVOKE', 'Admin Session Revocation'), ('STEP_UP_AUTH', 'Step-Up Authentication'), ('EMPLOYEE_OFFBOARDED', 'Employee Offboarded')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Tenant context (null for platform-level events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, help_text='User involved in this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=15)),
                ('notes', models.JSONField(blank=True, default=list, help_text='Chronological investigation notes [{timestamp, author, text}]')),
                ('actions_taken', models.JSONField(blank=True, default=list, help_text='Actions taken to contain/resolve [{timestamp, author, action}]')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affecting_incidents', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('related_events', models.ManyToManyField(blank=True, related_name='incidents', to='security.securityevent')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_incidents', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('password_min_length', models.PositiveIntegerField(default=8, help_text='Minimum password length')),
                ('password_require_uppercase', models.BooleanField(default=False, help_text='Require at least one uppercase letter')),
                ('password_require_number', models.BooleanField(default=False, help_text='Require at least one numeric digit')),
                ('password_require_special', models.BooleanField(default=False, help_text='Require at least one special character')),
                ('password_reject_common', models.BooleanField(default=True, help_text='Reject commonly used passwords')),
                ('mfa_required_for_admins', models.BooleanField(default=False, help_text='Require MFA for Owner, Admin, Finance, HR, Security roles')),
                ('mfa_required_for_all', models.BooleanField(default=False, help_text='Require MFA for all staff')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, help_text='Idle session timeout in minutes')),
                ('max_concurrent_sessions', models.PositiveIntegerField(default=5, help_text='Maximum concurrent sessions per user')),
                ('max_failed_login_attempts', models.PositiveIntegerField(default=5, help_text='Failed login attempts before temporary lockout')),
                ('lockout_duration_minutes', models.PositiveIntegerField(default=15, help_text='Lockout duration in minutes')),
                ('notify_on_failed_logins', models.BooleanField(default=True, help_text='Alert admins on repeated failed login attempts')),
                ('failed_login_alert_threshold', models.PositiveIntegerField(default=3, help_text='Number of failed logins before alerting admins')),
                ('notify_on_privilege_changes', models.BooleanField(default=True, help_text='Alert on role/permission changes')),
                ('notify_on_mfa_changes', models.BooleanField(default=True, help_text='Alert on MFA enable/disable')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Security Policy',
                'verbose_name_plural': 'Security Policies',
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('category', models.CharField(choices=[('AUDIT_LOGS', 'Audit Logs'), ('SECURITY_EVENTS', 'Security Events'), ('CUSTOMER_DATA', 'Customer Data'), ('SUPPORT_DATA', 'Support Data'), ('EXPORT_FILES', 'Export Files'), ('WORKFLOW_EXECUTIONS', 'Workflow Executions'), ('NOTIFICATIONS', 'Notifications'), ('SESSION_DATA', 'Session Data')], db_index=True, max_length=30)),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Number of days to retain data before eligible for cleanup')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_delete', models.BooleanField(default=False, help_text='If true, data will be automatically purged after retention period. If false, data is only flagged for review.')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'category'), name='unique_retention_per_category')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt Log',
                'verbose_name_plural': 'Login Attempt Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='security_lo_email_cec92f_idx'), models.Index(fields=['ip_address', 'created_at'], name='security_lo_ip_addr_12f554_idx'), models.Index(fields=['success', 'created_at'], name='security_lo_success_cbd213_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['restaurant', 'created_at'], name='security_se_restaur_d0a79a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='security_se_user_id_f7052a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'severity', 'created_at'], name='security_se_event_t_721987_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['restaurant', 'status', 'created_at'], name='security_se_restaur_57bd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['restaurant', 'severity'], name='security_se_restaur_2e8c6b_idx'),
        ),
    ]
