# Generated by Django 5.1.15 on 2026-08-16 17:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('order_number', models.CharField(db_index=True, help_text='Human-readable sequential order identifier (e.g. ORD-000001)', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLACED', 'Placed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', help_text='Current operational order lifecycle status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General order notes or special customer requests')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all order item line totals', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative final payable order total', max_digits=12)),
                ('created_by', models.ForeignKey(help_text='Authenticated staff employee who initiated the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, help_text='Dining floor table linked to this dine-in order (null for takeaway)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('item_name_snapshot', models.CharField(help_text='Immutable snapshot of MenuItem.name at order creation', max_length=200)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, help_text='Immutable snapshot of MenuItem.price at order creation', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Ordered item count (>= 1)')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Authoritative calculated line price (unit_price_snapshot * quantity)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text="Special preparation / dietary notes (e.g. 'Extra spicy', 'No dairy')")),
                ('menu_item', models.ForeignKey(blank=True, help_text='Reference to original catalog MenuItem record (can be null if item was deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(help_text='Parent order containing this line item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='orders_orde_restaur_17016b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', '-created_at'], name='orders_orde_restaur_7d58ee_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'table'], name='orders_orde_restaur_6f0c11_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('restaurant', 'order_number'), name='unique_order_number_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4ba133_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='check_positive_order_item_quantity'),
        ),
    ]
