# Generated by Django 5.1.15 on 2026-08-17 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Associated customer CRM profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, default='', help_text='Guest email for invoice and receipt dispatch', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, default='', help_text='Guest full name for unauthenticated/takeaway orders', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, default='', help_text='Guest contact phone for order tracking', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery')], db_index=True, default='DINE_IN', help_text='Fulfillment classification (Dine In, Takeaway, Delivery)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled pickup time for takeaway orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_session_id',
            field=models.CharField(blank=True, default='', help_text='QR table ordering session token', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('POS', 'Point of Sale'), ('ONLINE', 'Online Web'), ('QR', 'QR Table'), ('PHONE', 'Phone'), ('MANUAL', 'Manual')], db_index=True, default='POS', help_text='Channel where order originated', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Cryptographically secure token for public customer order tracking'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated staff employee or registered customer who initiated the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
