# Generated by Django 5.1.15 on 2026-08-16 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('actor_email', models.CharField(blank=True, default='', help_text='Email snapshot of actor', max_length=255)),
                ('actor_role', models.CharField(blank=True, default='', help_text='Active role at time of action', max_length=64)),
                ('actor_type', models.CharField(choices=[('USER', 'Human User'), ('SYSTEM', 'Automated Background Process')], default='USER', max_length=20)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGED', 'Password Changed'), ('ROLE_CHANGED', 'Role Changed'), ('PERMISSION_CHANGED', 'Permission Changed'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('STOCK_RECEIVED', 'Stock Received'), ('STOCK_WASTED', 'Stock Wasted'), ('EXPORT', 'Report / Data Export')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(choices=[('USER', 'User Account'), ('STAFF', 'Staff Profile'), ('RESTAURANT', 'Restaurant Tenant'), ('ROLE', 'Role & Permissions'), ('MENU_ITEM', 'Menu Item'), ('MENU_CATEGORY', 'Menu Category'), ('TABLE', 'Table Layout'), ('ORDER', 'Customer Order'), ('BILL', 'Invoice & Bill'), ('PAYMENT', 'Payment Settlement'), ('INVENTORY_ITEM', 'Inventory Item'), ('STOCK_MOVEMENT', 'Stock Movement'), ('SUPPLIER', 'Vendor Supplier'), ('PURCHASE_ORDER', 'Purchase Order'), ('NOTIFICATION', 'Notification'), ('REPORT', 'Report')], db_index=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable summary of the action')),
                ('before_data', models.JSONField(blank=True, default=dict, help_text='Previous state snapshot')),
                ('after_data', models.JSONField(blank=True, default=dict, help_text='Updated state snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Auxiliary contextual parameters')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='User initiating the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, help_text='Tenant context (null for platform/pre-auth events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='audit_audit_restaur_e60b17_idx'), models.Index(fields=['restaurant', 'entity_type', 'entity_id'], name='audit_audit_restaur_af636d_idx'), models.Index(fields=['restaurant', 'actor_user', 'created_at'], name='audit_audit_restaur_b25cc3_idx'), models.Index(fields=['restaurant', 'action'], name='audit_audit_restaur_eb5cd5_idx')],
            },
        ),
    ]
