# Generated by Django 5.1.15 on 2026-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('USER', 'User Account'), ('STAFF', 'Staff Profile'), ('RESTAURANT', 'Restaurant Tenant'), ('ROLE', 'Role & Permissions'), ('MENU_ITEM', 'Menu Item'), ('MENU_CATEGORY', 'Menu Category'), ('TABLE', 'Table Layout'), ('ORDER', 'Customer Order'), ('BILL', 'Invoice & Bill'), ('PAYMENT', 'Payment Settlement'), ('INVENTORY_ITEM', 'Inventory Item'), ('STOCK_MOVEMENT', 'Stock Movement'), ('SUPPLIER', 'Vendor Supplier'), ('PURCHASE_ORDER', 'Purchase Order'), ('NOTIFICATION', 'Notification'), ('REPORT', 'Report'), ('PROMOTION', 'Promotion'), ('COUPON', 'Coupon Code'), ('CAMPAIGN', 'Marketing Campaign'), ('MARKETING_CONSENT', 'Marketing Consent'), ('CUSTOMER_SEGMENT', 'Customer Segment'), ('DELIVERY', 'Delivery Order'), ('DELIVERY_ZONE', 'Delivery Zone'), ('DELIVERY_DRIVER', 'Delivery Driver')], db_index=True, max_length=50),
        ),
    ]
