# Generated by Django 5.1.15 on 2026-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditlog_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('USER', 'User Account'), ('STAFF', 'Staff Profile'), ('RESTAURANT', 'Restaurant Tenant'), ('ROLE', 'Role & Permissions'), ('MENU_ITEM', 'Menu Item'), ('MENU_CATEGORY', 'Menu Category'), ('TABLE', 'Table Layout'), ('ORDER', 'Customer Order'), ('BILL', 'Invoice & Bill'), ('PAYMENT', 'Payment Settlement'), ('INVENTORY_ITEM', 'Inventory Item'), ('STOCK_MOVEMENT', 'Stock Movement'), ('SUPPLIER', 'Vendor Supplier'), ('PURCHASE_ORDER', 'Purchase Order'), ('NOTIFICATION', 'Notification'), ('REPORT', 'Report'), ('PROMOTION', 'Promotion'), ('COUPON', 'Coupon Code'), ('CAMPAIGN', 'Marketing Campaign'), ('MARKETING_CONSENT', 'Marketing Consent'), ('CUSTOMER_SEGMENT', 'Customer Segment'), ('DELIVERY', 'Delivery Order'), ('DELIVERY_ZONE', 'Delivery Zone'), ('DELIVERY_DRIVER', 'Delivery Driver'), ('RECIPE', 'Recipe BOM'), ('STOCK_COUNT', 'Physical Stock Count'), ('INVENTORY_TRANSFER', 'Inventory Transfer'), ('WASTE_RECORD', 'Waste / Spoilage Record'), ('PURCHASE_REQUISITION', 'Purchase Requisition'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('PURCHASE_RETURN', 'Purchase Return'), ('SUPPLIER_INVOICE', 'Supplier Invoice'), ('SUPPLIER_CREDIT', 'Supplier Credit'), ('PROCUREMENT_BUDGET', 'Procurement Budget'), ('ACCOUNT', 'Chart of Accounts'), ('JOURNAL_ENTRY', 'General Journal Entry'), ('CASH_SESSION', 'Cash Drawer Session'), ('BANK_ACCOUNT', 'Bank Account'), ('BANK_RECONCILIATION', 'Bank Reconciliation'), ('EXPENSE', 'Expense Record'), ('FINANCIAL_PERIOD', 'Financial Period')], db_index=True, max_length=50),
        ),
    ]
