# Generated by Django 5.1.15 on 2026-08-16 17:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('bill_number', models.CharField(db_index=True, help_text='Sequential human-readable bill/invoice number (e.g. BILL-000001)', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('VOID', 'Void')], db_index=True, default='DRAFT', help_text='Current billing lifecycle status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of all bill line items before deductions and additions', max_digits=12)),
                ('discount_type', models.CharField(choices=[('NONE', 'None'), ('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='NONE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage or fixed discount value input', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed currency discount deduction', max_digits=12)),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Service charge percentage applied', max_digits=5)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed service charge currency amount', max_digits=12)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of applicable tax percentage at finalization', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed tax currency amount', max_digits=12)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Currency rounding adjustment applied to reach round grand total', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative total amount payable by customer', max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative sum of settled payments', max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining unpaid balance', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Billing / invoice remarks or customer instructions')),
                ('created_by', models.ForeignKey(help_text='Employee/cashier who generated the bill', on_delete=django.db.models.deletion.PROTECT, related_name='generated_bills', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Source order being billed', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='orders.order')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this financial record', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('item_name_snapshot', models.CharField(help_text='Frozen catalog item name at billing time', max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, help_text='Frozen unit price at billing time', max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity billed', validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Computed line total (unit_price * quantity)', max_digits=12)),
                ('bill', models.ForeignKey(help_text='Parent bill record', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
                ('order_item', models.ForeignKey(blank=True, help_text='Original source order item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI / QR Code'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', help_text='Tender method used for transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Net amount applied towards bill settlement', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_tendered', models.DecimalField(blank=True, decimal_places=2, help_text='Gross cash tendered by customer for change calculation', max_digits=12, null=True)),
                ('change_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Change returned to customer', max_digits=12)),
                ('reference', models.CharField(blank=True, default='', help_text='External payment reference, card last 4 digits, or transaction ID', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique client idempotency token preventing double billing', max_length=128, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='SUCCESS', max_length=20)),
                ('bill', models.ForeignKey(help_text='Bill being settled', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.bill')),
                ('received_by', models.ForeignKey(help_text='Cashier or staff member processing payment', on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization receiving payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('name', models.CharField(help_text='Tax name (e.g. VAT, GST, City Tax)', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Percentage tax rate (e.g. 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('restaurant', models.ForeignKey(help_text='Restaurant owning this tax policy', on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['restaurant', 'status'], name='billing_bil_restaur_b0ab28_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['restaurant', 'created_at'], name='billing_bil_restaur_ac6fe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('restaurant', 'bill_number'), name='unique_bill_number_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['restaurant', 'status'], name='billing_pay_restaur_62f789_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['restaurant', 'idempotency_key'], name='billing_pay_restaur_92c954_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_tax_rule_per_restaurant'),
        ),
    ]
