# Generated by Django 5.1.15 on 2026-08-16 16:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Display title for the category', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Optional summary or notes for category')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Deterministic display rank in menus and POS terminals')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates whether this category is active in the menu catalog')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this category', on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Commercial item title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed ingredients, recipe notes, or dietary descriptions')),
                ('price', models.DecimalField(decimal_places=2, help_text='Authoritative unit selling price in restaurant currency', max_digits=10)),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text="Immediate orderability toggle (86'd / out-of-stock toggle)")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Catalog presence toggle (Inactive items are hidden from live operations)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Deterministic display rank within the assigned category')),
                ('category', models.ForeignKey(help_text='Assigned category for sorting, routing, and reporting', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.menucategory')),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this menu item', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_menuca_restaur_fe7c15_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'display_order'], name='menu_menuca_restaur_a133c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_category_name_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'category'], name='menu_menuit_restaur_6c96a2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available'], name='menu_menuit_restaur_fa3149_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_active'], name='menu_menuit_restaur_98d8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'display_order'], name='menu_menuit_restaur_cb4167_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='check_positive_menu_item_price'),
        ),
    ]
