# Generated by Django 5.1.15 on 2026-08-16 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('resource', models.CharField(db_index=True, help_text='Target domain resource (e.g., orders, menu, tables, billing)', max_length=64)),
                ('action', models.CharField(db_index=True, help_text='Permitted action (e.g., view, create, update, delete, bump, pay)', max_length=64)),
                ('code', models.CharField(db_index=True, help_text='Unique permission code in format `resource.action`', max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('name', models.CharField(help_text='Human-readable role title', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Programmatic role slug (e.g., MANAGER, WAITER)', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='System-defined roles cannot be deleted')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant UUID for custom roles, or null for global system roles', null=True)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted to this role', related_name='roles', to='rbac.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Restaurant/Tenant UUID')),
                ('active_role', models.ForeignKey(blank=True, help_text='Currently active role for permission scoping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rbac.role')),
                ('assigned_roles', models.ManyToManyField(blank=True, help_text='All roles assigned to the user within this tenant', related_name='memberships', to='rbac.role')),
                ('user', models.ForeignKey(help_text='User belonging to this tenant organization', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('code', 'tenant_id'), name='unique_role_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantmembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant_id'), name='unique_user_tenant_membership'),
        ),
    ]
