# Generated by Django 5.1.15 on 2026-08-17 15:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0002_order_customer_order_guest_email_order_guest_name_and_more'),
        ('restaurants', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Motorcycle / Scooter'), ('CAR', 'Car / Van'), ('BICYCLE', 'Bicycle'), ('WALKER', 'On Foot')], default='BIKE', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'On Delivery'), ('OFFLINE', 'Offline')], db_index=True, default='AVAILABLE', max_length=20)),
                ('active_deliveries_count', models.PositiveIntegerField(default=0)),
                ('total_completed_deliveries', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(help_text='Restaurant tenant employing this courier', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_drivers', to='restaurants.restaurant')),
                ('staff_profile', models.OneToOneField(help_text='Associated employment staff profile', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='staff.staffprofile')),
            ],
            options={
                'verbose_name': 'Delivery Driver',
                'verbose_name_plural': 'Delivery Drivers',
                'ordering': ['availability_status', 'staff_profile__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active status flag')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Preparation'), ('PREPARING', 'In Kitchen Preparation'), ('READY_FOR_DISPATCH', 'Ready for Dispatch'), ('ASSIGNED', 'Driver Assigned'), ('PICKED_UP', 'Picked Up by Driver'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Successfully Delivered'), ('FAILED', 'Delivery Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current operational delivery state', max_length=30)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('landmark', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('delivery_instructions', models.TextField(blank=True, default='')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Authoritative delivery fee charged on this order', max_digits=10)),
                ('delivery_pin', models.CharField(blank=True, default='', help_text='Cryptographically generated 4-to-6 digit delivery verification PIN', max_length=6)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked registered customer CRM account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='customers.customer')),
                ('order', models.OneToOneField(help_text='Parent customer order being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fulfillment', to='orders.order')),
                ('restaurant', models.ForeignKey(help_text='Tenant organization owning this delivery', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='restaurants.restaurant')),
                ('assigned_driver', models.ForeignKey(blank=True, help_text='Fleet courier assigned to deliver this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='delivery.deliverydriver')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Staff or system user who triggered this operational event', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(help_text='Delivery record being audited', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.delivery')),
            ],
            options={
                'verbose_name': 'Delivery Event',
                'verbose_name_plural': 'Delivery Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Zone display title (e.g. Downtown / Zone A)', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('postal_codes', models.JSONField(blank=True, default=list, help_text="List of matched postal codes or prefixes (e.g. ['10001', '10002', '10003'])")),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Standard delivery charge for orders delivered to this zone', max_digits=10)),
                ('minimum_order', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Minimum order subtotal required for delivery to this zone', max_digits=10)),
                ('maximum_order', models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum order value cap', max_digits=10, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=30, help_text='Average transit duration in minutes from restaurant to this zone')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Evaluation priority order when an address matches multiple zones (higher number takes precedence)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(help_text='Restaurant organization owning this delivery zone', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Matched geographic delivery zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryzone'),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('label', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='HOME', max_length=20)),
                ('recipient_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('landmark', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(help_text='Customer profile owning this saved address', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='delivery_cu_custome_a791f2_idx'), models.Index(fields=['postal_code'], name='delivery_cu_postal__96d218_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['restaurant', 'availability_status'], name='delivery_de_restaur_bbf21f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydriver',
            index=models.Index(fields=['restaurant', 'is_active'], name='delivery_de_restaur_97ff77_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryevent',
            index=models.Index(fields=['delivery', 'created_at'], name='delivery_de_deliver_c068c3_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['restaurant', 'is_active'], name='delivery_de_restaur_645c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['restaurant', 'priority'], name='delivery_de_restaur_7623ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryzone',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_zone_name_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['restaurant', 'status'], name='delivery_de_restaur_a7c197_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['restaurant', '-created_at'], name='delivery_de_restaur_336c07_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['restaurant', 'assigned_driver'], name='delivery_de_restaur_4a461e_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['restaurant', 'postal_code'], name='delivery_de_restaur_ef89b6_idx'),
        ),
    ]
