# Generated by Django 5.1.15 on 2026-08-16 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('email', models.EmailField(db_index=True, help_text="User's primary email address for authentication", max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Consecutive failed login attempts count for lockout enforcement')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Timestamp until which the account remains locked', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw reset token', max_length=64, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this reset token has already been consumed')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration timestamp (default: 15 minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the issued refresh token for rotation validation', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address where session originated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw browser User-Agent string')),
                ('device_info', models.CharField(blank=True, help_text='Parsed device or browser identifier', max_length=255)),
                ('is_revoked', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this session has been terminated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Session expiration timestamp')),
                ('user', models.ForeignKey(help_text='Authenticated user owning this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_revoked', 'expires_at'], name='accounts_us_user_id_08d954_idx')],
            },
        ),
    ]
