# Generated by Django 5.1.15 on 2026-08-16 18:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('card_number', models.CharField(db_index=True, max_length=32)),
                ('secret_code', models.CharField(help_text='Hashed or secured redemption code', max_length=64)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('DEPLETED', 'Depleted'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='customers.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Initial Issuance'), ('LOAD', 'Top Up Balance'), ('REDEEM', 'Payment Redemption'), ('REFUND', 'Refund Restoration'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRATION', 'Expired Balance'), ('CANCELLATION', 'Card Cancellation')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount delta', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_type', models.CharField(blank=True, default='MANUAL', max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.giftcard')),
            ],
            options={
                'verbose_name': 'Gift Card Transaction',
                'verbose_name_plural': 'Gift Card Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('points_balance', models.IntegerField(default=0)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_redeemed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Loyalty Account',
                'verbose_name_plural': 'Loyalty Accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(default='Rewards & VIP Club', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('points_enabled', models.BooleanField(default=True)),
                ('earning_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earned per 1.00 base spend currency', max_digits=6)),
                ('redemption_enabled', models.BooleanField(default=True)),
                ('redemption_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Monetary value per 1 point (e.g. 0.05 = 100 points -> $5.00)', max_digits=6)),
                ('min_points_redemption', models.PositiveIntegerField(default=50)),
                ('points_expiration_enabled', models.BooleanField(default=False)),
                ('points_expiration_days', models.PositiveIntegerField(default=365)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Points Earned'), ('REDEEM', 'Points Redeemed'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRE', 'Points Expired'), ('REVERSAL', 'Refund Reversal'), ('BONUS', 'Bonus Points')], db_index=True, max_length=20)),
                ('points', models.IntegerField(help_text='Points delta: positive for earn, negative for redeem')),
                ('balance_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, default='MANUAL', max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loyalty_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField(help_text='Ordering rank: 1 is lowest/starter tier')),
                ('qualification_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime spend required to qualify for this tier', max_digits=12)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points earning multiplier (e.g. 1.25x)', max_digits=4)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Permanent member discount percentage on orders', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_tiers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Membership Tier',
                'verbose_name_plural': 'Membership Tiers',
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.membershiptier'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('reward_type', models.CharField(choices=[('FIXED_DISCOUNT', 'Fixed Amount Off'), ('PERCENTAGE_DISCOUNT', 'Percentage Off'), ('FREE_ITEM', 'Free Item')], default='FIXED_DISCOUNT', max_length=30)),
                ('points_cost', models.PositiveIntegerField(help_text='Points needed to redeem this reward')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['points_cost'],
            },
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('restaurant', 'card_number'), name='unique_card_number_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='membershiptier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_tier_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='membershiptier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'rank'), name='unique_tier_rank_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.UniqueConstraint(fields=('restaurant', 'customer'), name='unique_loyalty_account_per_customer'),
        ),
    ]
