# Generated by Django 5.1.15 on 2026-08-17 14:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('segment_type', models.CharField(choices=[('ALL_CUSTOMERS', 'All Registered Customers'), ('NEW_CUSTOMERS', 'New Customers (Registered < 30 days)'), ('REGULAR_CUSTOMERS', 'Regular Customers (3+ Visits)'), ('VIP_CUSTOMERS', 'VIP High-Spenders'), ('INACTIVE_CUSTOMERS', 'Inactive / At-Risk Customers'), ('HIGH_VALUE_CUSTOMERS', 'Top 10% Lifetime Spend'), ('CUSTOM', 'Custom Dynamic Rules')], default='CUSTOM', max_length=30)),
                ('min_spend', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum total lifetime spend required', max_digits=12)),
                ('min_visits', models.PositiveIntegerField(default=0, help_text='Minimum dining visits count required')),
                ('inactive_days', models.PositiveIntegerField(default=0, help_text='Days since last dining visit to consider lapsed/inactive')),
                ('is_active', models.BooleanField(default=True)),
                ('loyalty_tiers', models.ManyToManyField(blank=True, related_name='targeted_segments', to='loyalty.membershiptier')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='restaurants.restaurant')),
                ('tags', models.ManyToManyField(blank=True, related_name='targeted_segments', to='customers.customertag')),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email Marketing'), ('SMS', 'SMS Text Message'), ('PUSH', 'In-App Push Notification')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('GRANTED', 'Opted In (Granted)'), ('REVOKED', 'Opted Out (Revoked)')], default='GRANTED', max_length=20)),
                ('source', models.CharField(default='POS_REGISTRATION', help_text='Origin of consent (e.g. POS, ONLINE_BOOKING, CUSTOMER_PORTAL)', max_length=100)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consents', to='customers.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consents', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Marketing Consent',
                'verbose_name_plural': 'Marketing Consents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('promotion_type', models.CharField(choices=[('PERCENTAGE_DISCOUNT', 'Percentage Off Total/Items'), ('FIXED_DISCOUNT', 'Fixed Currency Amount Off'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('FREE_ITEM', 'Complimentary Item')], default='PERCENTAGE_DISCOUNT', max_length=30)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage value (0-100) or fixed currency amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Evaluation priority: higher number evaluated first (e.g. 100 > 10)')),
                ('stackable', models.BooleanField(default=False, help_text='Can be stacked alongside other non-coupon discounts')),
                ('coupon_required', models.BooleanField(default=False, help_text='Requires valid coupon code entry at checkout')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum subtotal spend required to activate promotion', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Ceiling cap on calculated percentage discounts', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total times this promotion can be redeemed (null for unlimited)', null=True)),
                ('per_customer_limit', models.PositiveIntegerField(default=1, help_text='Maximum redemptions allowed per individual customer')),
                ('daily_usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum redemptions allowed in a single calendar day', null=True)),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
                ('target_audience_type', models.CharField(choices=[('ALL', 'All Customers'), ('SPECIFIC_CUSTOMERS', 'Selected Customers'), ('CUSTOMER_TAGS', 'Customer Tags (e.g. VIP, Corporate)'), ('CUSTOMER_SEGMENT', 'Customer Segment'), ('LOYALTY_TIER', 'Membership Loyalty Tier'), ('FIRST_ORDER', 'First-Time Customers'), ('RETURNING', 'Returning Customers (2+ Orders)'), ('INACTIVE_CUSTOMERS', 'Inactive Customers (Lapsed Visits)')], default='ALL', max_length=30)),
                ('target_inactive_days', models.PositiveIntegerField(default=60, help_text='Days of dining inactivity required for INACTIVE_CUSTOMERS targeting')),
                ('target_item_type', models.CharField(choices=[('ALL_ITEMS', 'Entire Order / All Items'), ('SPECIFIC_ITEMS', 'Specific Menu Items'), ('CATEGORIES', 'Specific Menu Categories')], default='ALL_ITEMS', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='promotions', to='menu.menucategory')),
                ('target_customers', models.ManyToManyField(blank=True, related_name='targeted_promotions', to='customers.customer')),
                ('target_loyalty_tiers', models.ManyToManyField(blank=True, related_name='targeted_promotions', to='loyalty.membershiptier')),
                ('target_menu_items', models.ManyToManyField(blank=True, related_name='promotions', to='menu.menuitem')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='marketing.customersegment')),
                ('target_tags', models.ManyToManyField(blank=True, related_name='targeted_promotions', to='customers.customertag')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum total times this coupon code can be redeemed', null=True)),
                ('per_customer_limit', models.PositiveIntegerField(default=1, help_text='Maximum times this coupon code can be redeemed per customer')),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='restaurants.restaurant')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='marketing.promotion')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification Banner'), ('EMAIL', 'Email Broadcast'), ('SMS', 'SMS Text Alert')], default='IN_APP', max_length=20)),
                ('title', models.CharField(help_text='Headline or email subject', max_length=200)),
                ('message_template', models.TextField(help_text='Marketing message content body')),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='restaurants.restaurant')),
                ('target_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.customersegment')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='marketing.promotion')),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Authoritative currency amount discounted', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False, help_text='True if order was cancelled or voided and redemption reversed')),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_promotion_usages', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to='billing.bill')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='marketing.coupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to='orders.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='marketing.promotion')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Promotion Usage',
                'verbose_name_plural': 'Promotion Usages',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (No Consent / Inactive)')], default='SENT', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key ensuring idempotency: {campaign_id}:{customer_id}:{channel}', max_length=128, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='marketing.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_delivery_logs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Campaign Delivery Log',
                'verbose_name_plural': 'Campaign Delivery Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='marketing_c_campaig_241cbd_idx'), models.Index(fields=['customer', 'status'], name='marketing_c_custome_0bb95e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customersegment',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_segment_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='marketingconsent',
            constraint=models.UniqueConstraint(fields=('restaurant', 'customer', 'channel'), name='unique_customer_channel_consent'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['restaurant', 'status', 'start_at', 'end_at'], name='marketing_p_restaur_947abd_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['restaurant', 'coupon_required', 'status'], name='marketing_p_restaur_c2fb73_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['restaurant', 'code', 'status'], name='marketing_c_restaur_ce6829_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('restaurant', 'code'), name='unique_coupon_code_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['restaurant', 'status', 'start_at'], name='marketing_c_restaur_9aac2e_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['restaurant', 'promotion', 'customer', 'is_reversed'], name='marketing_p_restaur_9ce43d_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['restaurant', 'coupon', 'customer', 'is_reversed'], name='marketing_p_restaur_605275_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['restaurant', 'order', 'is_reversed'], name='marketing_p_restaur_acce9e_idx'),
        ),
    ]
