# Generated by Django 5.1.15 on 2026-08-16 18:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('allow_order_cancellation', models.BooleanField(default=True, help_text='Allow staff to cancel active orders')),
                ('cancellation_window_minutes', models.PositiveIntegerField(default=10, help_text='Window in minutes during which placed orders can be voided/cancelled')),
                ('require_order_confirmation', models.BooleanField(default=False, help_text='Require manager or head waiter confirmation before dispatch to KDS')),
                ('allow_table_orders', models.BooleanField(default=True, help_text='Allow dine-in ordering by table assignment')),
                ('allow_takeaway', models.BooleanField(default=True, help_text='Allow takeaway / parcel ordering')),
                ('default_prep_time_minutes', models.PositiveIntegerField(default=15, help_text='Standard preparation time target')),
                ('kds_warning_threshold_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before a kitchen ticket turns amber/warning')),
                ('kds_critical_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before a kitchen ticket turns red/critical')),
                ('auto_refresh_interval_seconds', models.PositiveIntegerField(default=15, help_text='KDS polling / reconnect interval in seconds')),
                ('tax_enabled', models.BooleanField(default=True, help_text='Whether tax calculation is enabled on bills')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default tax rate percentage (e.g. 5.00 for 5%)', max_digits=5)),
                ('tax_name', models.CharField(default='GST / VAT', help_text='Label printed on receipts (e.g. GST, VAT, Sales Tax)', max_length=50)),
                ('tax_registration_number', models.CharField(blank=True, default='', help_text='Official Tax Registration or GSTIN number', max_length=64)),
                ('tax_inclusive_pricing', models.BooleanField(default=False, help_text='Menu item prices already include taxes')),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for finalized tax invoices', max_length=10)),
                ('receipt_prefix', models.CharField(default='RCP', help_text='Prefix for payment receipts', max_length=10)),
                ('invoice_footer_notes', models.TextField(blank=True, default='Thank you for dining with us!', help_text='Footer notice printed on customer receipts')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow inventory consumption below zero')),
                ('require_wastage_reason', models.BooleanField(default=True, help_text='Require mandatory textual reason when recording stock wastage')),
                ('low_stock_threshold_default', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default minimum quantity threshold for low-stock triggers', max_digits=10)),
                ('po_approval_required', models.BooleanField(default=True, help_text='Require manager approval before purchase orders can be received')),
                ('po_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Orders above this amount strictly require manager approval', max_digits=12)),
                ('default_delivery_lead_days', models.PositiveIntegerField(default=3, help_text='Expected delivery lead time in days for new POs')),
                ('inventory_alerts_enabled', models.BooleanField(default=True)),
                ('order_alerts_enabled', models.BooleanField(default=True)),
                ('procurement_alerts_enabled', models.BooleanField(default=True)),
                ('restaurant', models.OneToOneField(help_text='Tenant owner of these operational configurations', on_delete=django.db.models.deletion.CASCADE, related_name='operational_settings', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Configuration',
                'verbose_name_plural': 'Restaurant Configurations',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light'), ('SYSTEM', 'System')], default='DARK', max_length=20)),
                ('time_format', models.CharField(choices=[('12H', '12-Hour (AM/PM)'), ('24H', '24-Hour')], default='12H', max_length=10)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('table_density', models.CharField(choices=[('COMPACT', 'Compact'), ('COMFORTABLE', 'Comfortable')], default='COMFORTABLE', max_length=20)),
                ('user', models.OneToOneField(help_text='User owner of these preferences', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
