# Generated by Django 5.1.15 on 2026-08-17 14:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='cover_image_url',
            field=models.CharField(blank=True, default='', help_text='Hero cover banner image URL for public restaurant storefront', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='guest_checkout_enabled',
            field=models.BooleanField(default=True, help_text='Allow guest diners to place orders without creating a password account'),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='max_online_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1000.00'), help_text='Maximum cart amount allowed for online orders', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='min_online_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required for online orders', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='online_ordering_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle enabling customer digital ordering'),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='qr_ordering_enabled',
            field=models.BooleanField(default=True, help_text='Enable QR table code dine-in ordering'),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Short commercial slogan or cuisine description', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='takeaway_ordering_enabled',
            field=models.BooleanField(default=True, help_text='Enable online takeaway & pickup orders'),
        ),
    ]
