# Generated by Django 5.1.15 on 2026-08-17 15:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_restaurantconfiguration_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Standard base delivery fee when no zone override applies', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='delivery_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle enabling doorstep delivery fulfillment'),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='estimated_delivery_buffer_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Average transit transit buffer added to preparation time for estimates'),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='free_delivery_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), help_text='Order subtotal threshold granting free delivery fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurantconfiguration',
            name='max_delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Maximum radial delivery distance coverage', max_digits=6),
        ),
    ]
